name: Bypass PR approval rules

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if hungmai-anz has approved
        run: |
          if [[ "${{ github.event.review.user.login }}" == "hungmai-anz" && "${{ github.event.review.state }}" == "approved" ]]; then
            echo "hungmai-anz approved the PR. Bypassing approval count.";
            exit 0;  # Allow the PR to bypass approval rules
          fi
          exit 1;  # Fail the job if not approved by hungmai-anz
